name: 'CI: Lint, Test & Build'

on:
  push:
    branches: [main]
    paths: ['server/**', 'public/**', '.dev/**']
  pull_request:
    branches: [main]
    paths: ['server/**', 'public/**', '.dev/**']

jobs:
  ci-job:
    name: Lint, Test & Build Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'

      - name: Run lint
        run: make lint

      - name: Run tests
        run: make test

      - name: Run build
        run: make build
